### ISSUE TITLE
Changing measurement units doesn't update values for existing guitar objects.

### ISSUE THREAD

**Issue by rares-fodor** [rodrigocfd/string-tension-calc#10]
<h2>Description</h2>

I noticed that the string tension values don't update for existing guitar objects when changing to a different measurement unit. This only seems to be an issue with the version available at [rodrigocfd.github.io/string-tension-calc/](https://rodrigocfd.github.io/string-tension-calc/).

Running the project locally (up to date with origin/vue3) produces expected results and the values are updated correctly.

<h2> Screenshots </h2>

<h3>Github.io instance (seems wrong)</h3>

![image](https://github.com/rodrigocfd/string-tension-calc/assets/56951209/fb824982-2e39-4f50-8847-194cac5afe5f)

<h3>Local instance (works fine)</h3>

![image](https://github.com/rodrigocfd/string-tension-calc/assets/56951209/cabaccd1-22f9-45e9-9809-8274b5a5eee1)

**Comment by rodrigocfd** [comment]
Recently I refactored the internal store, and I forgot that, when changing the unit, we must recalculate all tensions of all strings in all guitars. I believe it's fixed how.

Let me know if it works.

**Comment by rares-fodor** [comment]
All good! Thanks
