### ISSUE TITLE
Please add acoustic guitar sets

### ISSUE THREAD

**Issue by why-trv** [rodrigocfd/string-tension-calc#11]
First of all, this is just great - by far the best string tension calculator I've seen, thank you so much!

Can you please add acoustic sets?

**Comment by rodrigocfd** [comment]
> Can you please add acoustic sets?

I'd love to, but the elastic coefficients of the strings are different, and the ratio between string length and gauge is also probably different. So the polynomial expressions I use would lead to wrong results.

**Comment by why-trv** [comment]
> I'd love to, but the elastic coefficients of the strings are different, and the ratio between string length and gauge is also probably different. So the polynomial expressions I use would lead to wrong results.

Got it, thanks for your response. Having only read through the readme and not the actual code, I thought it was based on D'Addario's unit weights.
Do you mind if I ask what is the benefit of your approach compared to just using the UWs and the tension formula?

**Comment by rodrigocfd** [comment]
I do use the tension formula, but the unit weights are calculated with a polynomial equation, so I don't have to manually write each number. Plus  this allows me to extrapolate to 8+ strings and gauges D'Addario doesn't offer.

**Comment by why-trv** [comment]
Cool! I guess if you derived the polynomial coefficients from the unit weights, the same could be done for bronze strings and their unit weights, couldn't it?

By the way, I believe they provide the values for gauges as low as 7. Maybe that wasn't the case earlier (?)
(https://www.daddario.com/globalassets/pdfs/accessories/tension_chart_13934.pdf)

**Comment by rodrigocfd** [comment]
> I guess if you derived the polynomial coefficients from the unit weights, the same could be done for bronze strings and their unit weights, couldn't it?

Yes, but I has no use to me. Feel free to fork this project and make an acoustic guitar version of it.

> By the way, I believe they provide the values for gauges as low as 7. Maybe that wasn't the case earlier (?)

Maybe. I started this project with jQuery around 2016, so I don't really remember.

**Comment by blfuentes** [comment]
> Cool! I guess if you derived the polynomial coefficients from the unit weights, the same could be done for bronze strings and their unit weights, couldn't it?
> 
> By the way, I believe they provide the values for gauges as low as 7. Maybe that wasn't the case earlier (?) (https://www.daddario.com/globalassets/pdfs/accessories/tension_chart_13934.pdf)
I have a similar webtool using materials' density to calculate the tension, but I do think there are more things involved. I've implemented two different methods and the values I get are not 100% accurate.
https://github.com/blfuentes/guitarstring-tension-calculator/blob/master/src/Calculator.DLL/GuitarString.cs

![image](https://github.com/rodrigocfd/string-tension-calc/assets/5121778/c38fe6fb-56b6-47aa-8f35-c12b6bc12ca2)
![image](https://github.com/rodrigocfd/string-tension-calc/assets/5121778/3be30e91-e897-43c6-bffc-a3c98e9d3d88)

**Comment by rodrigocfd** [comment]
> I have a similar webtool using materials' density to calculate the tension, but I do think there are more things involved. I've implemented two different methods and the values I get are not 100% accurate.

In my method, I used a polynomial curve which is an *approximation* to the actual unit weights. It's very close, but it's not *exact*... so that small difference could be on my side. I don't know about your method, but to be 100% sure, just use the exact value of the UW provided by D'Addario chart in the formula.
